# Generated by Django 4.2 on 2023-08-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transaction_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_time',
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_created',
            field=models.DateTimeField(default='2023-08-16T23:12:46'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='time_updated',
            field=models.DateTimeField(default='2023-08-16T23:12:46'),
        ),
    ]
