# Generated by Django 4.2 on 2023-08-16 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_transaction_date_remove_transaction_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
