# Generated by Django 4.2 on 2023-08-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_time_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='time_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='time_updated',
            field=models.DateTimeField(),
        ),
    ]
